import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
      }],
      // eslint-config-next 16 turns these react-compiler correctness rules on as
      // errors. They flag long-established, working patterns across the app
      // (mount effects, fetch-on-mount, ref reads in hook returns). Proper fixes
      // are a separate refactor — keep them visible as warnings, not build breakers.
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/purity": "warn",
    },
  },
  {
    // Node CommonJS helper scripts legitimately use require().
    files: ["scripts/**/*.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    // Prod-build check output (NEXT_DIST_DIR=.next-build-check) — same
    // generated bundles as .next, linting them OOMs and floods with errors.
    ".next-build-check/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Self-hosted Monaco assets (generated by scripts/copy-monaco.js, gitignored).
    // These vendored worker bundles are 500KB+ minified files — linting them
    // blows the V8 heap (OOM, exit 134). Not our source; skip them.
    "public/monaco/**",
  ]),
]);

export default eslintConfig;
